routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SyarikatController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('syarikat', SyarikatController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Syarikat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Syarikat extends Model
{
    use HasFactory;

    protected $table = 'syarikats';

    protected $fillable = ['nama_syarikat', 'alamat', 'no_tel'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SyarikatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Syarikat;
use Illuminate\Http\Request;

class SyarikatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $syarikats = Syarikat::all();
        return view('syarikat.index', ['syarikats' => $syarikats]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('syarikat.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $syarikat = $this->validate(request(), [
            'nama_syarikat' => 'required',
            'alamat' => 'required',
            'no_tel' => 'required|numeric'
        ]);

        Syarikat::create($syarikat);
        return redirect('/syarikat');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $syarikat = Syarikat::find($id);
        return view('syarikat.show', ['syarikat' => $syarikat]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $syarikat = Syarikat::find($id);
        return view('syarikat.edit', ['syarikat' => $syarikat]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $syarikat = Syarikat::find($id);
        $syarikat->update($request->only('nama_syarikat', 'alamat', 'no_tel'));
        return redirect('/syarikat');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $syarikat = Syarikat::find($id);
        $syarikat->delete();
        return redirect('/syarikat');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Syarikat
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('syarikat.index') }}">
                                        Senarai
                                    </a>
                                    <a class="dropdown-item" href="{{ route('syarikat.create') }}">
                                        Tambah
                                    </a>

                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>

resources/views/syarikat/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="mt-5">Maklumat Syarikat</h2>
        <p>Berikut adalah maklumat terperinci syarikat</p>
        <form action="{{ route('syarikat.store') }}" method="post">
            @csrf
            <div class="form-group">
                <label for="nama_syarikat">Nama Syarikat:</label>
                <input type="text" class="form-control" id="nama_syarikat" name="nama_syarikat"
                    placeholder="contoh: ABC Sdn Bhd">
            </div>
            <div class="form-group">
                <label for="alamat">Alamat:</label>
                <input type="text" class="form-control" id="alamat" name="alamat"
                    placeholder="No 90, Jalan Mak Lagam">
            </div>
            <div class="form-group mb-5">
                <label for="no_tel">No Tel:</label>
                <input type="number" class="form-control" id="no_tel" name="no_tel" placeholder="contoh: 098689292">
            </div>
            <button type="button" onclick="history.back()" class="btn btn-primary">Back</button>
            <button type="submit" class="btn btn-success">Simpan</button>
        </form>
    </div>
@endsection

resources/views/syarikat/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h2 class="mt-5">Kemaskini Maklumat Syarikat</h2>
        <p>Kemaskini maklumat terperinci syarikat</p>
        <form action="{{ route('syarikat.update', $syarikat->id) }}" method="post">
            @method('put')
            @csrf
            <div class="form-group">
                <label for="nama_syarikat">Nama Syarikat:</label>
                <input type="text" class="form-control" id="nama_syarikat" name="nama_syarikat"
                    value="{{ $syarikat->nama_syarikat }}">
            </div>
            <div class="form-group">
                <label for="alamat">Alamat:</label>
                <input type="text" class="form-control" id="alamat" name="alamat" value="{{ $syarikat->alamat }}">
            </div>
            <div class="form-group mb-5">
                <label for="no_tel">No Tel:</label>
                <input type="number" class="form-control" id="no_tel" name="no_tel" value="{{ $syarikat->no_tel }}">
            </div>
            <button type="button" onclick="history.back()" class="btn btn-primary">Back</button>
            <button type="submit" class="btn btn-success">Kemaskini</button>

        </form>
    </div>
@endsection

resources/views/syarikat/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="">Senarai Syarikat</h2>
        <p>Ini adalah senarai ringkas syarikat</p>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama Syarikat</th>
                    <th>Alamat</th>
                    <th>No Tel</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($syarikats as $num => $syarikat)
                    <tr>
                        <td>{{ $num + 1 }}</td>
                        <td>{{ $syarikat->nama_syarikat }}</td>
                        <td>{{ $syarikat->alamat }}</td>
                        <td>{{ $syarikat->no_tel }}</td>
                        <td>
                            <a href="{{ route('syarikat.show', $syarikat->id) }}" class="btn btn-success btn-sm">View</a>
                            <a href="{{ route('syarikat.edit', $syarikat->id) }}" class="btn btn-primary btn-sm">Edit</a>
                            <form action="{{ route('syarikat.destroy', $syarikat->id) }}" method="post">
                                @csrf
                                <input type="hidden" name="_method" value="delete">
                                <button class="btn btn-danger btn-sm" type="submit"
                                    onclick="return confirm('Confirm to DELETE?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/syarikat/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="mt-5">Maklumat Syarikat</h2>
        <p>Berikut adalah maklumat terperinci syarikat</p>
        <form action="/action_page.php">
            <div class="form-group">
                <label for="usr">Nama Syarikat:</label>
                <input type="text" class="form-control" id="usr" name="username"
                    value="{{ $syarikat->nama_syarikat }}">
            </div>
            <div class="form-group">
                <label for="alamat">Alamat:</label>
                <input type="text" class="form-control" id="alamat" name="alamat" value="{{ $syarikat->alamat }}">
            </div>
            <div class="form-group mb-5">
                <label for="no_tel">No Tel:</label>
                <input type="text" class="form-control" id="no_tel" name="no_tel" value="{{ $syarikat->no_tel }}">
            </div>
            <button type="button" onclick="history.back()" class="btn btn-primary">Back</button>
        </form>
    </div>
@endsection